apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  labels:
    app.kubernetes.io/name: zookeeper-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log
  labels:
    app.kubernetes.io/name: zookeeper-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-jaas-config
data:
  zookeeper_jaas.conf: |
    Server {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       user_super="broker-secret"
       user_broker="broker-secret";
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:5.5.2
        ports:
        - containerPort: 2181
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "384Mi"
            cpu: "250m"        
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/var/lib/zookeeper/jaas/zookeeper_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -DrequireClientAuthScheme=sasl"
        volumeMounts:
        - name: data
          mountPath: "/var/lib/zookeeper/data"          
        - name: log
          mountPath: "/var/lib/zookeeper/log"
        - name: jaas-config
          mountPath: "/var/lib/zookeeper/jaas" 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-data
      - name: log
        persistentVolumeClaim:
          claimName: zookeeper-log
      - name: jaas-config
        configMap:
          name: zookeeper-jaas-config
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
